#:kivy 1.0.9

<LyraGame>:
    canvas:
        Rectangle:
            pos: 0, self.center_y / 2.5
            size: self.width, 5
        Rectangle:
            pos: self.center_x / 2.5, 0
            size: 5, self.height

    Label:
        font_size: 70
        center_x: root.width / 4
        top: root.top - 50
        text: "0"

    Label:
        font_size: 70
        center_x: root.width * 3 / 4
        top: root.top - 50
        text: "0"
